/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_omico_telegram_tdlib_Jni */

#ifndef _Included_me_omico_telegram_tdlib_Jni
#define _Included_me_omico_telegram_tdlib_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_omico_telegram_tdlib_Jni
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_omico_telegram_tdlib_Jni_init
  (JNIEnv *, jclass);

/*
 * Class:     me_omico_telegram_tdlib_Jni
 * Method:    createNativeClient
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_omico_telegram_tdlib_Jni_createNativeClient
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
